name: Run Python script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml

      - name: Run the Python script
        run: python export.py

      - name: Upload log file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: script_log
          path: script_log.log

      - name: Upload XML file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: import_file
          path: import.xml
